//-----------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//------------------------------------------------------------------------
export enum Feature {
    JobTemplate = 0,
    JobPosting = 1,
    Assessment = 2,
    OfferManagement = 3,
    Prospect = 4,
    SkypeInterview = 5,
    CandidateReccomendation = 6,
    JobReccomendation = 7,
    TalentCompanion = 8,
    PositionManagement = 9,
    CustomActivies = 10,
    BroadbeanIntegration = 11,
    Dashboard = 12,
    JobApproval = 13,
    Analytics = 14,
    EmailTemplate = 15,
    SearchEngineOptimization = 16,
    TermsAndConditions = 17,
    LinkedInIntegration = 18,
    EEO = 19,
    ProspectRecommendation = 20,
    RelevanceSearch = 21,
    ActivityAudience = 22,
    ApplyWithLinkedIn = 23,
    InclusiveHiring = 24,
    BroadbeanSetup = 25,
    JobCreationWizard = 26,
    TalentSourceTracking = 27,
    SilverMedalist = 28,
    ServiceAccount = 29,
}
