//-----------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//-----------------------------------------------------------------------

using System;
using Newtonsoft.Json;

namespace MS.GTA.ServicePlatform.GlobalService.Contracts.Client
{
    /// <summary>
    /// A physical Service Fabric cluster.  
    /// </summary>
    /// <remarks>
    /// The document id is generated by documentDB upon creation.
    /// The document partition is the datacenter.
    /// </remarks>
    public sealed class PhysicalCluster
    {
        /// <summary>
        /// Gets or sets the Azure geography boundary, such as unitedstates.
        /// </summary>
        [JsonProperty(PropertyName = "geography")]
        public string Geography { get; set; }

        /// <summary>
        /// Gets or sets the Azure datacenter, such as WestUS.
        /// </summary>
        [JsonProperty(PropertyName = "datacenter")]
        public string Datacenter { get; set; }

        /// <summary>
        /// Gets or sets the public URI of the cluster, which is used to route requests 
        /// to environments within this compute.
        /// </summary>
        [JsonProperty(PropertyName = "publicUri")]
        public Uri PublicUri { get; set; }

        /// <summary>
        /// Gets or sets the management URI of the cluster, which is used to route 
        /// service fabric management requests to this compute.
        /// </summary>
        [JsonProperty(PropertyName = "managementUri")]
        public Uri ManagementUri { get; set; }
        
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the value describing the type of cluster.
        /// </summary>
        [JsonProperty(PropertyName = "clusterType")]
        public PhysicalClusterType ClusterType { get; set; }

        /// <summary>
        /// Gets or sets the value of the ClusterId.
        /// </summary>
        [JsonProperty(PropertyName = "clusterId")]
        public string ClusterId { get; set; }
    }
}
