//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum ActivityAudience {
    HiringTeam = 0,
    InternalCandidates = 1,
    ExternalCandidates = 2,
    AllCandidates = 3,
}
