//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface Address {
    AddressLine1?: string;
    AddressLine2?: string;
    City?: string;
    State?: string;
    Country?: CountryCode;
    PostalCode?: string;
}
