//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ApplicationNote extends TalentBaseContract {
    id?: string;
    text?: string;
    visibility?: CandidateNoteVisibility;
    ownerObjectId?: string;
    ownerName?: string;
    ownerEmail?: string;
    createdDate?: Date;
    noteType?: CandidateNoteType;
}
