//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ApplicantProfile extends Person {
    id?: string;
    guid?: string;
    b2cObjectId?: string;
    isInternal?: boolean;
    status?: CandidateStatus;
    statusReason?: CandidateStatusReason;
    externalSource?: CandidateExternalSource;
    preferredPhone?: CandidatePreferredPhone;
    gender?: CandidateGender;
    ethnicOrigin?: CandidateEthnicOrigin;
    attachments?: ApplicantAttachment[];
    alertOnApplicationChange?: boolean;
    extendedAttributes?: { [key: string]: string; };
    workExperience?: WorkExperience[];
    education?: Education[];
    skillSet?: string[];
    talentSource?: TalentSource;
}
