//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum ApplicationPermission {
    ReadNote = 0,
    CreateNote = 1,
    CreateOffer = 2,
    ReadApplication = 3,
    UpdateApplication = 4,
    DeleteApplication = 5,
    RejectApplicant = 6,
    ViewAllActivities = 7,
    UpdateAllActivities = 8,
}
