//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ApplicationSchedule {
    id?: string;
    stage?: JobStage;
    scheduleEventId?: string;
    scheduleState?: JobApplicationScheduleState;
    application?: Application;
    stageOrder?: number;
    activityOrdinal?: number;
    activitySubOrdinal?: number;
    scheduleAvailabilities?: ScheduleAvailability[];
}
