//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ApplicantAttachment {
    id?: string;
    documentType?: CandidateAttachmentDocumentType;
    type?: CandidateAttachmentType;
    name?: string;
    description?: string;
    reference?: string;
    userAction?: UserAction;
    isJobApplicationAttachment?: boolean;
    uploadedBy?: Person;
    uploadedDateTime?: Date;
}
