//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum AppPermission {
    ReadTalentPool = 0,
    CreateTalentPool = 1,
    ReadTemplate = 2,
    CreateTemplate = 3,
    CreateJob = 4,
    ReadEmailTemplate = 5,
    CreateEmailTemplate = 6,
    AccessAdminCenter = 7,
    ViewAllJobs = 8,
    ViewAllJobApplications = 9,
    ViewAllTalentPools = 10,
    ViewAllTemplates = 11,
    UpdateAllCandidates = 12,
    ViewAnalytics = 13,
}
