//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum ArtifactType {
    PDF = 0,
    DOC = 1,
    JPG = 2,
    DOCX = 3,
    AVI = 4,
    MP4 = 5,
}
