//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum AssessmentReportType {
    Unspecified = 0,
    BackgroundCheck = 1,
    Skill = 2,
    Personality = 3,
}
