//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface AssessmentProject {
    id?: string;
    created?: string;
    title?: string;
    previewURL?: string;
    projectStatus?: string;
    instructions?: AssessmentInstructions;
    templates?: ExternalAssessment[];
    users?: AssessmentUser[];
    companyName?: string;
    jobTitle?: string;
    jobDescription?: string;
}
