//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface Attendee {
    user: GraphPerson;
    responseStatus?: InvitationResponseStatus;
    isResponseStatusInvalid?: boolean;
    responseComment?: string;
    responseDateTime?: Date;
    freeBusyStatus?: FreeBusyScheduleStatus;
}
