//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum CandidateReferenceSource {
    NotSpecified = 0,
    SuggestedByCandidate = 1,
    FirstConnection = 2,
    SecondConnection = 3,
    Other = 4,
}
