//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface CandidacyDetails {
    CandidacyId?: string;
    RequisitionId?: string;
    JobTitle?: string;
    Candidate?: CandidateInformation;
    HiringManager?: string;
    Recruiter?: string;
    CandidacyStage?: CandidacyStage;
    CandidacyStatus?: string;
    CandidateScore?: string;
}
