//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum CandidateAttachmentType {
    NotSpecified = 0,
    Resume = 1,
    CoverLetter = 2,
    Portfolio = 3,
    Video = 4,
}
