//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface CandidacySearchRequest {
    RequisitionFilter?: string[];
    StageFilter?: CandidacyStage;
    SearchText?: string;
    Skip?: number;
    Take?: number;
}
