//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum CandidacyStage {
    Incomplete = 0,
    Apply = 1,
    Screen = 2,
    Interview = 3,
    Offer = 4,
    PreOnboard = 5,
    Dispositioned = 6,
}
