//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum CandidateDisabilityStatus {
    NotSpecified = 0,
    Yes = 1,
    No = 2,
    DoNotWantToAnswer = 3,
}
