//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum CandidateEthnicOrigin {
    NotSpecified = 0,
    AfricanAmericanOrBlack = 1,
    AmericanIndianOrAlaskaNative = 2,
    Asian = 3,
    CaucasianOrWhile = 4,
    HispanicOrLatino = 5,
    MultiRacial = 6,
    NativeHawaiianOrOtherPacificIslander = 7,
    DoNotWantToAnswer = 8,
}
