//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface CandidateRecommendationFeedback {
    applicantId?: string;
    interested?: boolean;
    experience?: boolean;
    skills?: boolean;
    education?: boolean;
    other?: boolean;
}
