//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum CandidateStatusReason {
    Available = 0,
    HappyInPosition = 1,
    Blacklisted = 2,
    CandidateNotInterested = 3,
}
