//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface CandidatePersonalDetails extends TalentBaseContract {
    Gender?: CandidateGender;
    Ethnicity?: CandidateEthnicOrigin;
    DisabilityStatus?: CandidateDisabilityStatus;
    VeteranStatus?: CandidateVeteranStatus;
    MilitaryStatus?: CandidateMilitaryStatus;
    submittedOn?: Date;
    jobApplicationActivityId?: string;
}
