//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ConferenceInfo {
    id: string;
    subject: string;
    joinUrl: string;
    audio: AudioInfo;
    admitUsers: string;
    joinInfo: string;
    provider: ConferenceProvider;
}
