//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface DelegationRequestPagedResponse {
    items?: DelegationRequest[];
    nextPage?: string;
    previousPage?: string;
    pageNumber?: number;
    pageSize?: number;
    totalCount?: number;
}
