//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface Education {
    EducationId?: string;
    school?: string;
    degree?: string;
    fieldOfStudy?: string;
    grade?: string;
    description?: string;
    FromMonthYear?: Date;
    ToMonthYear?: Date;
}
