//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface EmailNotificationRequest {
    jobApplicationId: string;
    emailBody: string;
    emailFooter?: string;
    subject: string;
    mailTo: GraphPerson[];
    mailCC?: GraphPerson[];
}
