//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum EmailContentType {
    Subject = 0,
    Header = 1,
    EmailBody = 2,
    Closing = 3,
    Footer = 4,
}
