//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface EmailTemplateSettings {
    emailTemplateFooterText?: string;
    emailTemplatePrivacyPolicyLink?: string;
    emailTemplateTermsAndConditionsLink?: string;
    shouldDisableEmailEdits?: boolean;
    emailTemplateHeaderImgUrl?: string;
    modifiedBy?: Person;
    modifiedDateTime?: Date;
}
