//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum EmailTemplateTokens {
    Job_Title = 0,
    Candidate_Name = 1,
    Candidate_FirstName = 2,
    Company_Name = 3,
    Requester_Name = 4,
    Requester_Email = 5,
    Requester_Role = 6,
    HiringManager_Name = 7,
    HiringManager_Email = 8,
    Interview_Date = 9,
    Recruiter_Name = 10,
    Recruiter_Email = 11,
    Interview_Details_Table = 12,
    Call_To_Action_Link = 13,
    First_Interviewer_Name = 14,
    First_Interview_Time = 15,
    First_Interviewer_Job_Title = 16,
    Scheduler_Email = 17,
    Scheduler_Phone_Number = 18,
    Skype_Link = 19,
    Job_Id = 20,
    External_Job_Id = 21,
    Interviewer_FirstName = 22,
    Scheduler_First_Name = 23,
    ResponseStatus = 24,
    OfferExpiryDate = 25,
    OfferPackageURL = 26,
    Offer_Approver_Name = 27,
    Offer_Approver_Email = 28,
    Offer_Rejecter_Name = 29,
    Offer_Rejecter_Email = 30,
    Identity_Provider = 31,
    Identity_Provider_User_Name = 32,
    Job_Approver_Name = 33,
    Job_Approver_Email = 34,
    Job_Requester_Name = 35,
    Job_Requester_Email = 36,
}
