//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface EmailTemplate {
    id?: string;
    templateName: string;
    appName: string;
    templateType: string;
    isGlobal?: boolean;
    to?: string[];
    cc?: string[];
    bcc?: string[];
    subject?: string;
    header?: string;
    body?: string;
    closing?: string;
    footer?: string;
    isDefault?: boolean;
    isAutosent?: boolean;
    creator?: string;
    language?: string;
}
