//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum EntityType {
    JobOpeningPosition = 0,
    JobPost = 1,
    Candidate = 2,
    JobOpening = 3,
    JobApplication = 4,
}
