//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface EnvironmentSettings {
    id: string;
    templateSetting?: TemplateSettings;
    featureSettings?: FeatureSettings[];
    integrationSettings?: { [key: string]: IntegrationSetting; };
    offerSettings?: OfferSettings;
    eSignSettings?: ESignSettings;
    emailTemplateSettings?: EmailTemplateSettings;
    isPremium?: boolean;
}
