//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface EnvironmentMap {
    id?: string;
    autoNumber?: string;
    displayName?: string;
    alias?: string;
    brandingImages?: BrandingImage[];
    companyHeadquarters?: string;
    companyWebpage?: string;
    contactEmail?: string;
    phoneNumber?: string;
    environmentId?: string;
    tenantId?: string;
    privacyLink?: string;
    tosLink?: string;
    termsAndConditionsLink?: string;
    termsAndConditionsText?: string;
}
