//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum EnvironmentStatusCode {
    Unknown = 0,
    Installing = 1,
    Completed = 2,
    Upgrading = 3,
    Error = 4,
    NotStarted = 5,
    Deleting = 6,
    SoftDeleted = 7,
    Deleted = 8,
    Migrating = 9,
}
