//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum EnvironmentMode {
    Cds = 0,
    Falcon = 1,
    Both = 2,
    Xrm = 3,
    XrmAndFalcon = 4,
}
