//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ExpressionSuggestionCollection {
    id: string;
    name?: string;
    reason?: string;
    suggestion?: string;
    languageCode?: string;
    isEnabled?: boolean;
    hasDefault?: boolean;
    expressionSuggestions?: ExpressionSuggestion[];
}
