//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ExternalJobPost extends TalentBaseContract {
    id?: string;
    uri?: string;
    supplier?: JobPostSupplier;
    supplierName?: string;
    isRepostAvailable?: boolean;
    userAction?: UserAction;
    extendedAttributes?: { [key: string]: string; };
}
