//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ExternalAssessment {
    id?: string;
    created?: string;
    title?: string;
    previewUrl?: string;
    numberOfQuestions?: number;
    instructions?: AssessmentInstructions;
    questions?: AssessmentQuestion[];
}
