//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum ExternalSource {
    Internal = 0,
    MSDataMall = 1,
    LinkedIn = 2,
    Greenhouse = 3,
    ICIMS = 4,
}
