//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface FeedbackConfiguration {
    inheritFromHiringTeam?: boolean;
    viewFeedbackBeforeSubmitting?: boolean;
    editFeedbackAfterSubmitting?: boolean;
    feedbackReminderDelay?: FeedbackReminderDelay;
}

export enum FeedbackReminderDelay {
    None = 0,
    HalfDay = 1,
    OneDay = 2,
    TwoDays = 3,
    ThreeDays = 4,
    OneWeek = 5,
}
