//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface FeedbackNotes {
    submittedByOID: string;
    submittedByName: string;
    participantOID: string;
    participantName: string;
    submittedDateTime: Date;
    notes: string;
}
