//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface Feedback {
    stage?: JobStage;
    stageOrder?: number;
    strengthComment?: string;
    weaknessComment?: string;
    overallComment?: string;
    Status?: JobApplicationAssessmentStatus;
    statusReason?: JobApplicationAssessmentStatusReason;
    isRecommendedToContinue: boolean;
    feedbackProvider?: Delegate;
    jobApplicationID: string;
}
