//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface FeedbackSummary {
    Status?: JobApplicationAssessmentStatus;
    IsRecommendedToContinue?: boolean;
    SubmittedDateTime?: Date;
    InterviewerName?: string;
    OID?: string;
    RemindApplicable?: boolean;
    IsScheduleAvailable?: boolean;
    OverallComment?: string;
    FileAttachments?: FileAttachmentInfo[];
    SubmittedByOID?: string;
    SubmittedByName?: string;
    Notes?: string;
    NotesSubmittedByOID?: string;
    NotesSubmittedByName?: string;
    NotesSubmittedDateTime?: Date;
}
