//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface FileAttachmentInfo {
    fileId: string;
    name: string;
    blobURI: string;
    fileLabel?: string;
    description?: string;
    documentType?: string;
    fileSize?: number;
}
