//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum FlightingContextType {
    TenantObjectId = 0,
    UserObjectId = 1,
    Upn = 2,
    EnvironmentId = 3,
    Generic = 4,
}
