//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface FreeBusyRequest {
    userGroups: UserGroup[];
    utcStart?: Date;
    utcEnd?: Date;
    isRoom?: boolean;
}
