//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface HiringTeamMember extends Person {
    role: JobParticipantRole;
    userAction?: UserAction;
    title?: string;
    ordinal?: number;
    activities?: Activity[];
    feedbacks?: Feedback[];
    delegates?: Delegate[];
    metadata?: JobApplicationParticipantMetadata;
    isDeleteAllowed?: boolean;
    AddedOnDate?: Date;
}
