//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface IncentivePlanMetadata {
    organization: string;
    profession: string;
    discipline: string;
    standardTitle: string;
    incentivePlan: string;
    level: string;
}
