//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface Interviewer {
    PrimaryEmail?: string;
    Name?: string;
    OfficeGraphIdentifier?: string;
    Profession?: string;
    Role?: JobParticipantRole;
    InterviewerResponseStatus?: InvitationResponseStatus;
    InterviewerComments?: string;
}
