//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface InterviewDetails {
    JobApplicationID: string;
    CandidateName?: string;
    PositionTitle?: string;
    SchedulesForDay?: InterviewSchedule[];
}
