//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum InvitationResponseStatus {
    None = 0,
    Accepted = 1,
    TentativelyAccepted = 2,
    Declined = 3,
    Pending = 4,
    Sending = 5,
    ResendRequired = 6,
}
