//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface IVApplicationNote {
    id?: string;
    text?: string;
    ownerObjectId?: string;
    createdDate?: Date;
    ownerFullName?: string;
}
