//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface IVApplicant {
    JobApplicationId?: string;
    ExternalJobOpeningId?: string;
    ExternalJobApplicationId?: string;
    JobTitle?: string;
    Candidate?: CandidateInformation;
    HiringManager?: string;
    Recruiter?: string;
    participantRole?: JobParticipantRole;
    CurrentStage?: JobApplicationActivityType;
    JobDescription?: string;
}
