//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface IVPerson {
    objectId?: string;
    givenName?: string;
    middleName?: string;
    surname?: string;
    fullName?: string;
    email?: string;
    alternateEmail?: string;
    linkedIn?: string;
    linkedInAPI?: string;
    facebook?: string;
    twitter?: string;
    homePhone?: string;
    workPhone?: string;
    mobilePhone?: string;
    profession?: string;
}
