//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum IVRequisitionPilotType {
    PrePilot = 0,
    FirstRingPilot = 1,
    SecondRingPilot = 2,
    ThirdRingPilot = 3,
    FourthRingPilot = 4,
    FifthRingPilot = 5,
    SixthRingPilot = 6,
}
