//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface IVWorker {
    workerId?: string;
    profession?: string;
    name?: PersonName;
    fullName?: string;
    emailPrimary?: string;
    alias?: string;
    phonePrimary?: string;
    officeGraphIdentifier?: string;
    isEmailContactAllowed?: boolean;
}
