//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface JobApplicationHistoryMetadata {
    jobApplicationStatus?: JobApplicationStatus;
    jobApplicationDate?: Date;
    hiringTeamMember?: HiringTeamMember;
    jobTitle?: string;
    jobOpeningId?: string;
    jobApplicationId?: string;
    rank?: Rank;
    talentSource?: TalentSource;
}
