//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobApplicationStatusReason {
    New = 0,
    OfferPrepared = 1,
    OfferAccepted = 2,
    CandidateWithdrew = 3,
    PositionFilled = 4,
    PositionCancelled = 5,
    Application = 6,
    Education = 7,
    Experience = 8,
    SkillSet = 9,
    Competency = 10,
    Licensure = 11,
    Assessment = 12,
    OfferRejected = 13,
    SilverMedalist = 14,
    NicManagementExperience = 1001,
    NicJobRelatedEducation = 1002,
    NicOther = 1003,
    NicJobTechnicalFunctionalExperience = 1004,
    NicInconsistentJobHistory = 1005,
    NoRequiredQualification = 1006,
    OthersMoreQualified = 1007,
}
