//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobApplicationScheduleState {
    NotScheduled = 0,
    Purposed = 1,
    Invited = 2,
    Scheduled = 3,
}
