//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobApplicationActivityStatusReason {
    ProcessCreated = 0,
    ProcessCompleted = 1,
    Started = 2,
    Completed = 3,
    PositionFilled = 4,
    PositionCancelled = 5,
}
