//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface JobApplicationAssessmentReport {
    jobApplicationId: string;
    candidateGivenName: string;
    candidateSurname: string;
    externalAssessmentReportID: string;
    assessmentStatus: AssessmentStatus;
    assessmentURL: string;
    title: string;
    reportURL: string;
    results: JobApplicationAssessmentReportResult[];
    additionalInformation: string;
}
