//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobApplicationActivityArtifactType {
    File = 0,
    Email = 1,
    Meeting = 2,
    Comment = 3,
    Image = 4,
    URL = 5,
    Video = 6,
}
