//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface JobApplicationAssessmentReportResult {
    ScoreType: string;
    ScoreValue: string;
    ResultSubject: string;
    AdditionalInformation: string;
    AdditionalResultData: string;
}
