//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface JobApplicationMetadata {
    jobApplicationId?: string;
    externalJobOpeningId?: string;
    jobTitle?: string;
    jobDescription?: string;
    currentJobApplicationStageStatus?: JobApplicationStageStatus;
    currentJobOpeningStage?: JobStage;
    jobApplicationStatus?: JobApplicationStatus;
    candidate?: CandidateInformation;
    jobApplicationParticipants?: JobApplicationParticipant[];
    jobApplicationParticipantDetails?: IVWorker[];
    IsScheduleSentToCandidate?: boolean;
    HireType?: string;
    JobApplicationStatusReason?: JobApplicationStatusReason;
    isWobAuthenticated?: boolean;
}
