//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface JobMetadataRequest {
    jobStatuses?: JobOpeningStatus[];
    skip?: number;
    take?: number;
    searchText?: string;
    continuationToken?: string;
}
