//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface JobOpeningTemplateParticipant extends AADUser {
    userObjectId?: string;
    groupObjectId?: string;
    tenantObjectId?: string;
    isDefault?: boolean;
    canEdit?: boolean;
}
