//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobOfferStatusReason {
    New = 0,
    Draft = 1,
    Review = 2,
    Approved = 3,
    Published = 4,
    Accepted = 5,
    WithdrawnCandidateDispositioned = 6,
    NeedRevision = 7,
    WithdrawnOther = 8,
    Declined = 9,
    Closed = 10,
    Expired = 11,
}
