//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobOpeningPositionType {
    FullTime = 0,
    PartTime = 1,
    Contract = 2,
    Temporary = 3,
    Volunteer = 4,
}
