//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobOpeningSeniorityLevel {
    Default = 0,
    Internship = 1,
    EntryLevel = 2,
    Associate = 3,
    MidSeniorLevel = 4,
    Director = 5,
    Executive = 6,
}
