//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobOfferApprovalStatus {
    NotStarted = 0,
    Approved = 1,
    Sendback = 2,
    SentForReview = 3,
    WaitingForReview = 4,
    Skipped = 5,
}
