//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobOfferNonStandardReason {
    SalaryNegotiation = 0,
    BenefitsNegotiation = 1,
    LocationNegotiation = 2,
    CandidateInformation = 3,
    JobInformation = 4,
}
