//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobOfferEmailParticipantRole {
    HiringManager = 0,
    Recruiter = 1,
    Interviewer = 2,
    Contributor = 3,
    OfferCreator = 4,
    OfferRejector = 5,
}
