//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobOfferStatus {
    Active = 0,
    Inactive = 1,
    Pending = 2,
    Viewed = 3,
    Accepted = 4,
    Decline = 5,
}
