//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobOfferArtifactType {
    OfferLetter = 0,
    OtherDocument = 1,
    OfferLetterDocX = 2,
    OfferTemplate = 3,
}
