//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobPermission {
    UpdateJobDetails = 0,
    UpdateJobProcess = 1,
    ActivateJob = 2,
    CreateJobApproval = 3,
    CreateJobPosting = 4,
    CloseJob = 5,
    CreateApplicant = 6,
    DeleteJob = 7,
    CreateHiringTeam = 8,
}
