//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface JobParticipant {
    FullName?: string;
    Alias?: string;
    EmailPrimary?: string;
    OfficeGraphIdentifier?: string;
    TeamsIdentifier?: string;
    Role?: JobParticipantRole;
}
