//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum JobStage {
    Application = 0,
    Assessment = 1,
    Screening = 2,
    Interview = 3,
    Offer = 4,
    Prospect = 5,
}
