//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface LinkedXRMEnvironmentInformation {
    instanceId: string;
    instanceUrl: string;
    instanceApiUrl: string;
    createdTime: Date;
    modifiedTime: Date;
    hostNameSuffix: string;
    localeId: number;
    initialUserObjectId: string;
    friendlyName: string;
    uniqueName: string;
    domainName: string;
    hasAttractServiceEndpointConfigured: boolean;
}
