//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface MeetingInfo {
    id: string;
    userGroups: UserGroup;
    requester?: GraphPerson;
    scheduleEventId?: string;
    scheduleStatus?: ScheduleStatus;
    meetingDetails: MeetingDetails[];
    tenantId?: string;
    scheduleOrder?: number;
    InterviewerTimeSlotId: string;
}
