//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface MeetingAddress {
    type: string;
    postOfficeBox: string;
    street: string;
    city: string;
    state: string;
    countryOrRegion: string;
    postalCode: string;
}
