//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface MeetingDetails {
    id: string;
    subject?: string;
    description?: string;
    utcStart?: Date;
    utcEnd?: Date;
    location?: string;
    meetingLocation?: InterviewMeetingLocation;
    calendarEventId?: string;
    skypeOnlineMeetingRequired: boolean;
    onlineMeetingRequired: boolean;
    unknownFreeBusyTime?: boolean;
    status?: FreeBusyScheduleStatus;
    isTentative?: boolean;
    attendees: Attendee[];
    skypeOnlineMeeting?: SkypeSchedulerResponse;
    isDirty?: boolean;
    skypeMeetingType?: SkypeMeetingType;
    schedulerAccountEmail?: string;
    isPrivateMeeting?: boolean;
    isInterviewScheduleShared: boolean;
    isInterviewerNameShared: boolean;
    conference?: ConferenceInfo;
}
