//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum OfferDeclineReason {
    CompensationPackage = 0,
    NotGoodCultureFit = 1,
    JobTitle = 2,
    Relocation = 3,
    WithdrawInterest = 4,
    AcceptedAnotherOffer = 5,
    AcceptedAnotherOfferWithYourCompany = 6,
    Other = 7,
}
