//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum OfferFeatureName {
    ApprovalRequired = 0,
    ApprovalCommentRequired = 1,
    SequentialApproval = 2,
    ParallelApproval = 3,
    DeclineOffer = 4,
    OfferExpirationDate = 5,
    CustomRedirectUrl = 6,
    OnboardingRedirectRequired = 7,
}
