//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum OfferArtifactDocumentType {
    Doc = 0,
    DocX = 1,
    Pdf = 2,
    Html = 3,
    Jpg = 4,
    XlsX = 5,
    PptX = 6,
    Jpeg = 7,
    Png = 8,
    Txt = 9,
}
