//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum PackageStatusCode {
    Unknown = 0,
    Installing = 1,
    Upgrading = 2,
    Completed = 3,
    Error = 4,
    NotStarted = 5,
}
