//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum RequestStatus {
    Submitted = 0,
    Accepted = 1,
    Active = 2,
    Rejected = 3,
    Ended = 4,
    Revoked = 5,
}
