//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum Required {
    ForAll = 0,
    ForInternalyOnly = 1,
    ForExternalOnly = 2,
    No = 3,
}
