//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface Sample {
    deleteJobs?: boolean;
    job: Job;
    teams?: TeamMember[];
    candidates?: Applicant[];
    advanceStages?: { [key: string]: JobStage[]; };
    advanceStageOrder?: { [key: string]: number[]; };
    assessments?: { [key: string]: Feedback[]; };
    rejectedCandidates?: { [key: string]: JobApplicationStatusReasonPayload; };
}
