//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ScheduleInvitationRequestV2 {
    subject: string;
    emailContent: string;
    emailAttachmentFiles?: File[];
    emailAttachmentFileLabels?: string[];
    isInterviewTitleShared: boolean;
    isInterviewScheduleShared: boolean;
    primaryEmailRecipient: string;
    ccEmailAddressList?: string[];
    sharedSchedulesScheduleId?: string[];
    sharedSchedulesIsInterviewScheduleShared?: boolean[];
    sharedSchedulesIsInterviewerNameShared?: boolean[];

}
