//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ScheduleAttendee {
    userId?: string;
    userName?: string;
    scheduleEventId?: string;
    responseStatus?: InvitationResponseStatus;
    startTime?: Date;
}
