//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum ScheduleStatus {
    NotScheduled = 0,
    Saved = 1,
    Queued = 2,
    Sent = 3,
    FailedToSend = 4,
    Delete = 5,
}
