//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ScheduleEmailTemplate {
    id?: string;
    tenantId?: string;
    userObjectId?: string;
    templateName?: string;
    templateType?: TemplateType;
    isDefault?: boolean;
    isAutosent?: boolean;
    isTentative?: boolean;
    ccEmailAddressRoles?: JobParticipantRole[];
    ccEmailAddressList?: string[];
    bccEmailAddressRoles?: JobParticipantRole[];
    bccEmailAddressList?: string[];
    primaryEmailRecipients?: string[];
    subject?: string;
    emailContent?: string;
    emailTokenList?: EmailTemplateTokens[];
    fromAddressMode?: SendEmailFromAddressMode;
}
