//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface ScheduleInvitationDetails {
    requester?: GraphPerson;
    primaryEmailRecipients: string[];
    ccEmailAddressList?: string[];
    bccEmailAddressList?: string[];
    subject: string;
    emailContent: string;
    interviewDate?: string;
    startTime?: string;
    endTime?: string;
    location?: string;
    skypeMeetingUrl?: string;
    interviewTitle?: string;
    ScheduleId?: string;
    IsInterviewTitleShared?: boolean;
    IsInterviewScheduleShared?: boolean;
    IsInterviewerNameShared?: boolean;
}
