//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface SkypeOnlineMeetingExtension {
    id: string;
    type: string;
    onlineMeetingConfLink: string;
    onlineMeetingExternalLink: string;
    onlineMeetingInternalLink: string;
    ucMeetingSetting: string;
    ucInband: string;
    ucCapabilities: string;
    participantPassCode: string;
    tollNumber: string;
    tollFreeNumber: string;
    _links: SkypeLinks;
}
