//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface SkypeSchedulerResponse {
    joinUrl: string;
    onlineMeetingId: string;
    expirationTime: Date;
    subject: string;
    leaders: string[];
    attendees: string[];
    accessLevel: string;
    entryExitAnnouncement: string;
    automaticLeaderAssignment: string;
    onlineMeetingUri: string;
    organizerUri: string;
    phoneUserAdmission: string;
    lobbyBypassForPhoneUsers: string;
    etag: string;
    _links: SkypeLinks;
    _embedded: SkypeEmbedded;
}
