//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface StageScheduleEvent {
    JobApplicationId: string;
    TeamMembers: TeamMember[];
    Stage: JobStage;
    StageOrder?: number;
    Location?: string;
    Comment?: string;
    ScheduleEventId: string;
    ScheduleState: JobApplicationScheduleState;
    ScheduleType?: number;
    ScheduleAvailabilities?: ScheduleAvailability[];
    ScheduleDates?: string[];
    TimezoneName?: string;
}
