//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface StageActivity extends TalentBaseContract {
    id?: string;
    name?: string;
    displayName?: string;
    description?: string;
    ordinal?: number;
    subOrdinal?: number;
    audience?: ActivityAudience;
    isEnableForCandidate?: boolean;
    activityType?: JobApplicationActivityType;
    configuration?: string;
    scheduleEventId?: string;
    comment?: string;
    activityStatus?: JobApplicationActivityStatus;
    participants?: HiringTeamMember[];
    dueDateTime?: Date;
    plannedStartDateTime?: Date;
    required?: Required;
}
