//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface SuggestMeetingsRequest {
    interviewStartDateSuggestion: Date;
    interviewEndDateSuggestion: Date;
    timezone?: Timezone;
    panelInterview?: boolean;
    privateMeeting?: boolean;
    teamsMeeting?: boolean;
    meetingDurationInMinutes?: string;
    interviewersList?: UserGroup[];
    candidate?: GraphPerson;
}
