//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum TalentPoolPermission {
    ReadTalentPool = 0,
    UpdateTalentPool = 1,
    DeleteTalentPool = 2,
    AddCandidate = 3,
    DeleteCandidate = 4,
}
