//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum TalentApplicationRole {
    AttractAdmin = 0,
    OnboardAdmin = 1,
    LearnAdmin = 2,
    AttractRecruiter = 3,
    AttractHiringManager = 4,
    AttractReader = 5,
}
