//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface TalentSource extends TalentBaseContract {
    id?: string;
    name?: string;
    domain?: string;
    description?: string;
    talentSourceCategory?: OptionSetValue;
    referalReference?: Person;
}
