//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface TeamMember extends AADUser {
    Role: JobParticipantRole;
    UserAction: UserAction;
    IsMemberOfActivity: boolean;
}

export interface AADUser extends TalentBaseContract {
    name: string;
    id: string;
    title: string;
    email: string;
    given: string;
    mobilePhone: string;
    officeLocation: string;
    userPrincipalName: string;
    mailNickname?: string;
    externalWorkerId?: string;
    externalWorkerSource?: Source;
}
