//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface TemplateSettings {
    disableTemplateCreation?: boolean;
    defaultTemplateIds?: string[];
    modifiedBy?: Person;
    modifiedDateTime?: Date;
}
