//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export enum TemplateType {
    CandidateInterview = 0,
    CandidateInvite = 1,
    CandidateAvailability = 2,
    InterviewerMeeting = 3,
    InterviewerSummary = 4,
    InterviewerMeetingReminder = 5,
    InterviewerFeedbackReminder = 6,
    ReviewActivitiesTemplate = 7,
    OfferNotificationTemplate = 8,
    NewCandidateScheduler = 9,
    NotifySchedulerAcceptDecline = 10,
    RequestForFeedback = 11,
    RoomDeclineReminder = 12,
    PendingDeclinedResponseReminder = 13,
    ProspectCandidateApplyInvite = 14,
    InterviewInvitationFailed = 15,
    RequestForJobApproval = 16,
    NotifyJobApprovedToRequester = 17,
    NotifyJobDeniedToRequester = 18,
    RequestOfferApproval = 19,
    NotifyOfferApproved = 20,
    NotifyOfferRejected = 21,
    NotifyOfferPublishedToCandidate = 22,
    NotifyOfferWithdraw = 23,
    OfferExpiryReminder = 24,
    NotifyOfferDeclinedToRecruiter = 25,
    NotifyOfferDeclinedToHiringManager = 26,
    NotifyOfferAcceptedToRecruiter = 27,
    NotifyOfferAcceptedToHiringManager = 28,
    NotifyOfferExpired = 29,
    NotifyOfferApprovalToOfferCreator = 30,
    NotifyOfferRejectionToOfferCreator = 31,
    NotifyOfferCloseToRecruiter = 32,
    NotifyOfferCloseToHiringManager = 33,
    CandidateLoginFailed = 34,
    CandidateLoginInformation = 35,
    RequestForJobApprovalReminder = 36,
    NotifyApplicationRejectedToCandidate = 37,
}
