//---------------------------------------------------------------------------
// <copyright company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// This file is auto-generated by the MS.GTA.Talent/TalentContracts/ContractGenerator.tst script.
//---------------------------------------------------------------------------

export interface UserESignConfiguration {
    id?: string;
    oid?: string;
    refreshToken?: string;
    esignTypeSelected?: ESignType;
    tenantId?: string;
    environmentId?: string;
    emailAddress?: string;
    apiAccessPoint?: string;
    webAccessPoint?: string;
}
