//-----------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace ServicePlatform.GlobalService.Contracts.Client
{
    /// <summary>
    /// A cluster partition that identifies a logical compute boundary that is
    /// serviced by a single cluster (<see cref="PhysicalCluster"/>).
    /// </summary>
    /// <remarks>
    /// The document id is generated by documentDB upon creation.
    /// The document partition is the CNAME that services this cluster.
    /// </remarks>
    public sealed class LogicalCluster
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the physical cluster, which can be used
        /// to retrieve <see cref="PhysicalCluster"/> documents.
        /// </summary>
        [JsonProperty(PropertyName = "physicalClusterId")]
        public string PhysicalClusterId { get; set; }
        
        /// <summary>
        /// Gets or sets the public URI of the cluster, which is used to route requests 
        /// to environments within this compute.
        /// </summary>
        [JsonProperty(PropertyName = "publicUri")]
        public Uri PublicUri { get; set; }

        /// <summary>
        /// Gets or sets the management URI of the cluster, which is used to route 
        /// service fabric management requests to this compute.
        /// </summary>
        [JsonProperty(PropertyName = "managementUri")]
        public Uri ManagementUri { get; set; }
    }
}
