//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.GTA.Common.Common.Common.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.GTA.Common.Common.Common.Email.EmailStrings", typeof(EmailStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap D365BannerImage {
            get {
                object obj = ResourceManager.GetObject("D365BannerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:600px&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;img src=&apos;cid:{HeaderImage}&apos; width=&apos;700&apos; height=&apos;100&apos; /&gt;
        ///                &lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;div style=&apos;margin-left:60px&apos;&gt;
        ///                        &lt;h2&gt;Hi {CandidateName},&lt;/h2&gt;
        ///                        &lt;p&gt;
        ///                            Thank you for applying for the {PositionTitle} position.
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailMessageTemplate_Candidate {
            get {
                return ResourceManager.GetString("EmailMessageTemplate_Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:600px&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;img src=&apos;cid:{HeaderImage}&apos; width=&apos;700&apos; height=&apos;100&apos; /&gt;
        ///                &lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;div style=&apos;margin-left:60px&apos;&gt;
        ///                        &lt;h2&gt;Hi {CandidateName},&lt;/h2&gt;
        ///                        &lt;p&gt;
        ///                            Thank you for applying for the {PositionTitle} position.
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailMessageTemplate_CandidateInviteToTakeAssessment {
            get {
                return ResourceManager.GetString("EmailMessageTemplate_CandidateInviteToTakeAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;body&gt;
        ///        &lt;img src=&apos;cid:{HeaderImage}&apos;/&gt;
        ///        &lt;div style=&apos;margin-left:60px&apos;&gt;
        ///        &lt;h2&gt;
        ///           Hi {ReviewerName},
        ///        &lt;/h2&gt;
        ///        &lt;p&gt;I&apos;d like your feedback on a project of ours, {ProjectTitle}. &lt;/p&gt;
        ///        &lt;p&gt;Please take a few moments to let me know what went well and what needs improvement.&lt;/p&gt;      
        ///        &lt;p&gt;&lt;a href=&apos;{ReviewLink}&apos;&gt;Give Feedback&lt;/a&gt;&lt;/p&gt;
        ///        &lt;p&gt;Thanks!&lt;p&gt;
        ///        &lt;/div&gt;
        ///       {EmailFooterPrivateField}
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string EmailMessageTemplate_DefaultPerformanceFeedback {
            get {
                return ResourceManager.GetString("EmailMessageTemplate_DefaultPerformanceFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:600px&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;img src=&apos;cid:{HeaderImage}&apos; width=&apos;700&apos; height=&apos;100&apos; /&gt;
        ///                &lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;div style=&apos;margin-left:60px&apos;&gt;
        ///                        &lt;h2&gt;Hi {FirstName},&lt;/h2&gt;
        ///                        &lt;p&gt;Thanks for helping with our interviews for the {Position} . We’ve scheduled your interview with {Candidate}
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailMessageTemplate_Interview {
            get {
                return ResourceManager.GetString("EmailMessageTemplate_Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:600px&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;img src=&apos;cid:{HeaderImage}&apos; width=&apos;700&apos; height=&apos;100&apos; /&gt;
        ///                &lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;div style=&apos;margin-left:60px&apos;&gt;
        ///                        &lt;h2&gt;
        ///                            Hi {InterviewerName},
        ///                        &lt;/h2&gt;
        ///                        &lt;p&gt;Thanks for joining my interview team for the new {Pos [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailMessageTemplate_Interviewer {
            get {
                return ResourceManager.GetString("EmailMessageTemplate_Interviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body style=&quot;font-family:Arial&quot;&gt;
        ///    &lt;table style=&quot;width:575px; border-color:#C7C7C7; border-width:1px; border-spacing:0px; border-style:solid;&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr style=&quot;margin:0;padding:0&quot;&gt;
        ///                &lt;td style=&quot;margin:0;padding:0&quot;&gt;
        ///                    &lt;img src=&quot;cid:{HeaderImage}&quot; width=&quot;632&quot; height=&quot;30&quot; /&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;div style=&apos;margin: 40px 40px 25px 40px; font-size:14px; letter-spacing: 0.6px&apos;&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailMessageTemplate_ManagerInvite {
            get {
                return ResourceManager.GetString("EmailMessageTemplate_ManagerInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:600px&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;img src=&apos;cid:{HeaderImage}&apos; width=&apos;700&apos; height=&apos;120&apos; /&gt;
        ///                &lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;div style=&apos;margin-left:60px&apos;&gt;
        ///                        &lt;h2&gt;Hi {NewHireName},&lt;/h2&gt;
        ///                        &lt;p&gt;Welcome to {CompanyName}! We’ve put together some activities, contacts, and resources to help you
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailMessageTemplate_NewHire {
            get {
                return ResourceManager.GetString("EmailMessageTemplate_NewHire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:600px&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;img src=&apos;cid:{HeaderImage}&apos; width=&apos;700&apos; height=&apos;120&apos; /&gt;
        ///                &lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;div style=&apos;margin-left:60px&apos;&gt;
        ///                        &lt;h2&gt;
        ///                            Hi {ReviewerName},
        ///                        &lt;/h2&gt;
        ///                        &lt;p&gt;{Message}&lt;/p&gt;
        ///                        &lt;p&gt;&lt;a href=&apos;{Revi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailMessageTemplate_PerformanceFeedback {
            get {
                return ResourceManager.GetString("EmailMessageTemplate_PerformanceFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width:700px; background-color:#E6E6E6; padding: 25px 35px;&quot;&gt;
        ///&lt;tbody&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;
        ///&lt;img src=&apos;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARgAAAATCAYAAABLPhL7AAAAAXNSR0IArs4c6QAAE6ZJREFUeAHtmwt8VMXVwGfu7iZZQAMJrS98fApYA776QxSQKlVbKxW1Coi2RXwUpewmAXmpFfCrKCAh2cXfJ/hqK1VL9bMKggp+gga02NYXolKMoihKs0l4JCHZvXe+/7nJDWGTjQFB4s+Mbu6dOWfOnDlz5sw5Zy566zW9Dq82aohKUbQy8YVjjnjG7HIuT4HiNt96zksLWoK3w9ol0C6B754E/LuM01M5an7qqetKU2W9YZTTAo5Sxpj7tdYmNZ12SLsE2iXwXZOA9V2bcFuebzg8dmpb5q+dt3YJ7K0E/Hvb4UD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailMessageTemplateFooter {
            get {
                return ResourceManager.GetString("EmailMessageTemplateFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare for your interview.
        /// </summary>
        public static string EmailSubjectTemplate_Candidate {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate_Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CompanyName} has invited you to take an online assessment.
        /// </summary>
        public static string EmailSubjectTemplate_CandidateInviteToTakeAssessment {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate_CandidateInviteToTakeAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Requester} has requested feedback from you for {Reviewee}.
        /// </summary>
        public static string EmailSubjectTemplate_DefaultPerformanceFeedback {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate_DefaultPerformanceFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our interview team.
        /// </summary>
        public static string EmailSubjectTemplate_Interview {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate_Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get set up as an interviewer.
        /// </summary>
        public static string EmailSubjectTemplate_Interviewer {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate_Interviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A candidate has applied for {PositionTitle}.
        /// </summary>
        public static string EmailSubjectTemplate_ManagerInvite {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate_ManagerInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {CompanyName}!.
        /// </summary>
        public static string EmailSubjectTemplate_NewHire {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate_NewHire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Requester} has requested feedback from you for {Reviewee}.
        /// </summary>
        public static string EmailSubjectTemplate_PerformanceFeedback {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate_PerformanceFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{Footer_Text}&lt;/p&gt;.
        /// </summary>
        public static string EmailTemplate_FooterHtml {
            get {
                return ResourceManager.GetString("EmailTemplate_FooterHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img alt=&quot;Email header image&quot; src=&quot;{Header_Image_Url}&quot; /&gt;.
        /// </summary>
        public static string EmailTemplate_HeaderHtml {
            get {
                return ResourceManager.GetString("EmailTemplate_HeaderHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Company_Name} respects  your &lt;a aria-label=&quot;Privacy policy link&quot; href=&quot;{Privacy_Policy_Link}&quot;&gt;privacy&lt;/a&gt;..
        /// </summary>
        public static string EmailTemplate_PrivacyHtml {
            get {
                return ResourceManager.GetString("EmailTemplate_PrivacyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See our &lt;a aria-label=&quot;Terms and conditions link&quot; href=&quot;{Terms_And_Conditions_Link}&quot;&gt;terms of use&lt;/a&gt;..
        /// </summary>
        public static string EmailTemplate_TermsHtml {
            get {
                return ResourceManager.GetString("EmailTemplate_TermsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HcmBannerImage {
            get {
                object obj = ResourceManager.GetObject("HcmBannerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MicrosoftLogo {
            get {
                object obj = ResourceManager.GetObject("MicrosoftLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=windows-1256&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///    &lt;title&gt;Dynamics 365 for Talent&lt;/title&gt;
        ///    &lt;style&gt;
        ///        /* -------------------------------------
        ///              GLOBAL RESETS
        ///          ------------------------------------- */
        ///        img {
        ///            border: none;
        ///            -ms-interpolation-mode: bicubic;
        ///            max-width: 100%;
        ///        }
        ///
        ///        body {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReponsiveEmailLayout {
            get {
                return ResourceManager.GetString("ReponsiveEmailLayout", resourceCulture);
            }
        }
    }
}
