name: publish-common-to-github
on:
  [workflow_dispatch]
jobs:
  publish:
    name: common nuget publish to github packages
    runs-on: windows-latest
    defaults:
      run:
        working-directory: common/MS.GTA.CommonLibrary

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Pack
      run: nuget pack Nuget.nuspec
    - name: Publish
      run: nuget push "*.nupkg" -s https://nuget.pkg.github.com/microsoft/index.json -k ${{secrets.GITHUB_TOKEN}}
