name: build common

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: common # set common/ as working directory

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore MS.GTA.CommonLibrary/MS.GTA.CommonLibrary.sln
    - name: Build
      run: dotnet build MS.GTA.CommonLibrary/MS.GTA.CommonLibrary.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test MS.GTA.CommonLibrary/MS.GTA.CommonLibrary.sln --no-restore --verbosity normal
