name: build-common

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: common # set common/ as working directory

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.811

    - name: Install dependencies
      run: dotnet restore HR.TA.CommonLibrary/HR.TA.CommonLibrary.sln

    - name: Build
      run: dotnet build HR.TA.CommonLibrary/HR.TA.CommonLibrary.sln --configuration Release --no-restore

    - name: Unit Test
      run: dotnet test HR.TA.CommonLibrary/HR.TA.CommonLibrary.sln --no-build --configuration Release --verbosity m
