name: publish-common-to-github
on:
  [workflow_dispatch]
env:
  source-url: "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
jobs:
  publish:
    name: common nuget publish to github packages
    runs-on: windows-latest
    defaults:
      run:
        working-directory: common
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Add Github registry as source
      run: nuget sources Add https://nuget.pkg.github.com/microsoft/index.json -password $GITHUB_TOKEN -username notused -name "github" -StorePasswordInClearText
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore Packages
      run: nuget restore MS.GTA.CommonLibrary/MS.GTA.CommonLibrary.sln

    - name: Build Solution
      run: |
        msbuild.exe MS.GTA.CommonLibrary/MS.GTA.CommonLibrary.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"

    - name: Pack
      run: nuget pack MS.GTA.CommonLibrary/Nuget.nuspec

    - name: Publish
      run: nuget push "*.nupkg" -Source https://nuget.pkg.github.com/microsoft/index.json -ApiKey "${{ secrets.GITHUB_TOKEN }}"
