name: publish-common-to-github
on:
  [workflow_dispatch]

jobs:
  publish:
    name: common nuget publish to github packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: common
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.811

    - name: Pack
      run: dotnet pack MS.GTA.CommonLibrary/MS.GTA.Common/MS.GTA.Common.csproj --configuration Release

    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: MS.GTA.CommonLibrary/MS.GTA.Common/MS.GTA.Common.csproj
          NUGET_KEY: ${{secrets.GITHUB_TOKEN}}
          NUGET_SOURCE: https://nuget.pkg.github.com/microsoft/index.json
    
    # - name: Publish
    #   run: find ./MS.GTA.CommonLibrary/MS.GTA.Common/bin/Release -iname "*.nupkg" | xargs dotnet nuget push -s https://nuget.pkg.github.com/microsoft/index.json -k ${{secrets.GITHUB_TOKEN}}
