name: schedule-service-build

# Controls when the action will run. 
on:
  [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    defaults:
      run:
        working-directory: schedule-service # set schedule-service/ as working directory

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.811

      - name: Install dependencies
        env:
          TOKEN: ${{secrets.TOKEN}}
          USERNAME: ${{secrets.USERNAME}}
        run: dotnet restore HR-GTA-CaAsse-ATDYN-ScheduleService/MS.GTA.ScheduleService.sln

      - name: Build
        run: dotnet build HR-GTA-CaAsse-ATDYN-ScheduleService/MS.GTA.ScheduleService.sln --configuration Release --no-restore

      - name: Unit Test
        run: dotnet test HR-GTA-CaAsse-ATDYN-ScheduleService/MS.GTA.ScheduleService.sln --no-build --configuration Release --verbosity m
